

# Matrix inverse
$$
\begin{array}{l}
\mathbf{A} = \begin{bmatrix}
-2 & 6 \\
8 & -4
\end{bmatrix}
\\[10pt]
\det(\mathbf{A}) = ad - bc = (-2) \times (-4) - 8 \times 6 = -40
\\[10pt]
\det(\mathbf{A}) = -40 \neq 0 \quad \Rightarrow invertible
\\[10pt]
\mathbf{A}^{-1} = \frac{1}{\det(\mathbf{A})} \begin{bmatrix}
d & -b \\
-c & a
\end{bmatrix} = \frac{1}{-40} \begin{bmatrix}
-4 & -6 \\
-8 & -2
\end{bmatrix} = \begin{bmatrix}
0.1 & 0.15 \\
0.2 & 0.05
\end{bmatrix}
\end{array}
$$


# Eigenvector and eigenvalue
$$
\mathbf{A} = \begin{bmatrix}
0.9 & 0.2 \\
0.1 & 0.8
\end{bmatrix}
$$
## Eigenvalue
$$
\begin{array}{l}
Eigenvalue(\lambda) = det(A - \lambda I) = 0\\
\\[10pt]
det(\begin{bmatrix}
        0.9 & 0.2 \\
        0.1 & 0.8
    \end{bmatrix} - \lambda 
    \begin{bmatrix}
        1 & 0 \\
        0 & 1
    \end{bmatrix}) = 0\\
det(\begin{bmatrix}
        0.9 - \lambda & 0.2 \\
        0.1 & 0.8 - \lambda
    \end{bmatrix}) = 0\\
\\[10pt]
\to (0.9 - \lambda)(0.8 - \lambda) - 0.2*0.1 = 0\\
\to 0.72 - 1.7\lambda + \lambda^2 - 0.02 = 0\\
\to \lambda^2 - 1.7\lambda + 0.7 = 0\\
\Longrightarrow \begin{bmatrix} 
                    \lambda_1 = 1 \\ 
                    \lambda_2 = 0.7
                \end{bmatrix}\\
\end{array}
$$

## Eigenvectors

$$
\begin{array}{l}

Eigenvector (v): Av = \lambda v \Leftrightarrow (A − \lambda I)v = 0\\
\\[10pt]
Eigenvector for \lambda _1 = 1 :\\
(A -1*I)v = \begin{bmatrix}
                0.9 - 1 & 0.2 \\
                0.1 & 0.8 - 1
            \end{bmatrix} v
        = \begin{bmatrix}
                -0.1 & 0.2 \\
                0.1 & -0.2
            \end{bmatrix} v
        = 0\\
\to v_1 = \begin{bmatrix}
            1 \\
            0.5
        \end{bmatrix}\\
\\[10pt]
Eigenvector for \lambda _2 = 0.7 :\\
(A -0.7*I)v = \begin{bmatrix}
                0.9 - 0.7 & 0.2 \\
                0.1 & 0.8 - 0.7
            \end{bmatrix} v
        = \begin{bmatrix}
                0.2 & 0.2 \\
                0.1 & 0.1
            \end{bmatrix} v
        = 0\\
\to v_2 = \begin{bmatrix}
            1 \\
            -1
        \end{bmatrix}

\end{array}
$$

## Cosine Similarity
$$
\begin{array}{l}
Cosine Similarity: cs(x, y) =  \frac{ x . y}{\|x \| \| y \|} 
        = \frac{\sum_{1}^n x_i y_i}
        {\sqrt{\sum_{1}^n x_i^2} \sqrt{\sum_{1}^n y_i^2}}\\


\\[10pt]
\mathbf{x} = \begin{bmatrix} 1 \\ 2 \\ 3 \\ 4 \end{bmatrix}, \quad \mathbf{y} = \begin{bmatrix} 1 \\ 0 \\ 3 \\ 0 \end{bmatrix}\\

\\[10pt]
Dot Product x⋅y:\\
x⋅y=(1⋅1)+(2⋅0)+(3⋅3)+(4⋅0)=1+0+9+0=10\\

\\[10pt]
Norm \|x\| and \|y\| :\\
\| x \| = \sqrt{1^2 + 2^2 + 3^2 + 4^2} = \sqrt{1 + 4 + 9 + 16} = \sqrt{30}      \\
\| y \| = \sqrt{1^2 + 0^2 + 3^2 + 2^2} = \sqrt{1 + 0 + 9 + 0} = \sqrt{10}      \\

\\[10pt]
Cosine Similarity:      \\
cs(x, y) = \frac{ x . y}{\|x \| \| y \|} = \frac{10}{\sqrt{30}\sqrt{10}} = \frac{10}{\sqrt{300}} = \frac{1}{\sqrt{3}}

\end{array}
$$


# QUIZ

In [1]:
# 1
import numpy as np

def compute_vector_length(vector):

    len_of_vector = np.sqrt(np.sum(np.square(vector)))

    return len_of_vector

vector = np.array([-2, 4, 9, 21])
result = compute_vector_length(vector)
print(round(result, 2))

23.28


In [2]:
# 2
import numpy as np

def compute_dot_product(vector1, vector2):

    vector1 = np.array(vector1)
    vector2 = np.array(vector2)

    result = np.sum(vector1 * vector2)

    return result

v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
result = compute_dot_product(v1, v2)
print(round(result, 2))


4


In [3]:
# 3
import numpy as np

x = np.array ([[1, 2], [3, 4]])
k = np.array([1,2])

print(x.dot(k))

[ 5 11]


In [4]:
# 4
import numpy as np

x = np.array ([[-1, 2], [3, -4]])
k = np.array([1,2])

print(x@k)

[ 3 -5]


In [7]:
# 5
import numpy as np

def matrix_multi_vector(matrix, vector):

    matrix = np.array(matrix)
    vector = np.array(vector)

    result = matrix.dot(vector)

    return result

m = np.array ([[-1, 1, 1], [0, -4, 9]])
v = np.array ([0, 2, 1])
result = matrix_multi_vector(m, v)
print(result)

[3 1]


In [8]:
# 6
import numpy as np

def matrix_multi_vector(matrix, vector):

    matrix = np.array(matrix)
    vector = np.array(vector)

    result = matrix.dot(vector)

    return result

m1 = np.array ([[0, 1, 2], [2, -3, 1]])
m2 = np.array ([[1, -3],[6, 1], [0, -1]])
result = matrix_multi_vector(m1, m2)
print(result)

[[  6  -1]
 [-16 -10]]


In [9]:
# 7
import numpy as np

m1 = np.eye(3)
m2 = np.array ([[1, 1, 1],[2, 2, 2], [3, 3, 3]])
result = m1@m2
print(result)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [10]:
# 8
import numpy as np

m1 = np.eye(2)
m1 = np.reshape(m1 ,(-1,4))[0]
m2 = np.array ([[1, 1, 1, 1],[2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print(result)

[5. 5. 5. 5.]


In [12]:
# 9
import numpy as np

m1 = np.array ([[1, 2], [3, 4]])
m1 = np.reshape(m1 ,(-1,4), "F")[0]
m2 = np.array ([[1, 1, 1, 1],[2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print(result)

[29 29 29 29]


In [13]:
#  10
import numpy as np


def inverse_matrix(matrix):

    matrix = np.array(matrix)

    result = np.linalg.inv(matrix)

    return result

m1 = np.array([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


In [14]:
# 11
import numpy as np

def compute_eigenvalues_eigenvectors(matrix):

    matrix = np.array(matrix)

    eigenvalues, eigenvectors = np.linalg.eig(matrix)

    return eigenvalues, eigenvectors

matrix = np.array ([[0.9 , 0.2], [0.1, 0.8]])
eigenvalues , eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [15]:
# 12
x = np.array ([1, 2, 3, 4])
y = np.array ([1, 0, 3, 0])

def compute_cosine(v1, v2):
    v1 = np.array(v1)
    v2 = np.array(v2)

    dot_product = np.dot(v1, v2)
    norm_v1 = np.linalg.norm(v1)
    norm_v2 = np.linalg.norm(v2)

    cosine_similarity = dot_product / (norm_v1 * norm_v2)

    return cosine_similarity

result = compute_cosine(x,y)
print(round(result , 3))

0.577
